### ISSUE TITLE
？

### ISSUE THREAD

**Issue by bigchalizi** [q609262096/zq#1]
写了不要fork  fork我的库干嘛   跑中青阅读能改全吗  第111行改成自己的时长ck啊

**Comment by bigchalizi** [comment]
把fork的库删了 111行改成自己的时长ck就行

**Comment by q609262096** [comment]
> 把fork的库删了 111行改成自己的时长ck就行

好的，谢谢大佬

**Comment by bigchalizi** [comment]
> > 把fork的库删了 111行改成自己的时长ck就行
> 
> 好的，谢谢大佬

没事别乱fork用我的cookie跑就行

**Comment by q609262096** [comment]
> > > 把fork的库删了 111行改成自己的时长ck就行
> > 
> > 
> > 好的，谢谢大佬
> 
> 没事别乱fork用我的cookie跑就行

明白。原来一直找不到时长ck在哪填，后面会注意的。
